### ISSUE TITLE
When running train.py, why can't I get the same high accuracy as in train_search.py?

### ISSUE THREAD

**Issue by liqier** [guyuchao/DOTS#3]
Thanks for your work!
One question I hope can be answered: for the same data set and parameter settings, I run train.py with the best cell obtained by train_search.py. Why can't I get the same high accuracy as in train_search.py? 
Look forward to your reply.

**Comment by guyuchao** [comment]
The train_search.py optimizes the supernet which has more parameters and a complicated structure. The supernet has a better expressive ability than the searched cell at the cost of memory and computation overhead. It is normal to observe a better accuracy in training the supernet.
